### ISSUE TITLE
Passing parameter to nested ResponseEntity

### ISSUE THREAD

**Issue by halbano** [intridea/grape-entity#102]
Hi all, 

The requirements of my project are now forcing me to passing parameters to nested entities. 
I have an entity A and an entity B that show some information and needs the A identifier on the system to build them. 

module Services
  module Trips
    class TripPreviewResponseEntity < Grape::Entity
      expose :id
      expose :title
      expose :duration
      expose :total_price
      expose :description
      expose :details
      expose :destinations, using: Destinations::DestinationResponseEntity
    end
  end
end

In the example above I want to do something like that:       
expose :destinations, using: Destinations::DestinationResponseEntity, :trip_id => object.id

And in the nested Entity use the trip_id parameter option in this way:

expose :trip_info do |item,options|
        item.show(options[:trip_id])
end

But it's failing saying that object is not defined. Is there a way to perform this?
Thks in advance.

**Comment by calfzhou** [comment]
`object` is an instance attribute, cannot be accessed this way.

Even if you could get `object`, `expose` doesn't support custom options, it only accepts the following ones:
```ruby
    # All supported options.
    OPTIONS = [
      :as, :if, :unless, :using, :with, :proc, :documentation, :format_with, :safe, :if_extras, :unless_extras
    ].to_set.freeze
```

Thus it will fail and say `:trip_id is not a valid option`.

I'm also wondering how to pass custom options to nested exposures.

**Comment by Martin91** [comment]
@halbano @calfzhou If you want to pass custom options to nested exposures, may be you can try:

```ruby
expose :destinations, documentation: {is_array: true} do |trip, options|       // ignore :documentation option if your association is just single one
  Destinations::DestinationResponseEntity.represent trip.destinations, options.merge(custom_field_name: custom_field_value)  # use merge to extend options and then pass the whole options to the nested entity
end
```

and then you can access them:

```ruby
expose :trip_info do |item,options|
  item.show(options[:custom_field])
end
```

I have tried it successfully in my project. Hope helpful for you!

**Comment by calfzhou** [comment]
looks good, thanks @Martin91

**Comment by dblock** [comment]
Can someone contribute this to the README please?

**Comment by Martin91** [comment]
@dblock ok, I will submit a new PR for this skill.

**Comment by Martin91** [comment]
@dblock I have submitted a new PR #133 , please review and at me if any question. Although the document has explained how to pass additional option to nested exposure, but I think the way is not a very good practice, because developers are required to use `Entity.represent` method and runtime exposure, which is not natural. But I have no time to consider a good solution, is it better to provide another option in `Entity.expose` method, and the gem is responsible for merging options? For example, let us assume the new option key is `:merge`.

```ruby
# new version of  `expose` supports `:merge` option, which is used to extend options hash
expose :destinations, using: Destinations::DestinationResponseEntity, merge: {custom_field_name: custom_field_value}, documentation: {is_array: true}

expose :trip_info do |item,options|
  item.show(options[:custom_field])
end
```

**Comment by dblock** [comment]
I would be in favor of a nested `expose`.

**Comment by dmitry** [comment]
Looks like can be closed?! Direct `represent` is enough.

**Comment by dblock** [comment]
Agreed, closing.
