### ISSUE TITLE
How do I fetch request params inside an Entity ?

### ISSUE THREAD

**Issue by bachetouane** [intridea/grape-entity#115]
Hello,

I'm trying to get the request params inside an Entity file. What is the best way to do that ?
The documentation says it should be in options[:env]['grape.request.params'] but it doesn't seem to work. 
I could only get the params using options[:env]["rack.request.query_hash"] but I had to manually convert the number params to integers for me to be able to use them.
Is there a better way to get those params ?

**Comment by dblock** [comment]
I think you have to pass it into `expose`, something like this:

```ruby
class Status < Grape::Entity
  expose :user do |instance, options|
    options[:request]
  end
end
```

```ruby
present s, with: Status, request: request
```

You'll have better luck with questions on the [Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape).
