### ISSUE TITLE
`only` option doesn't work

### ISSUE THREAD

**Issue by durnoyabsurd** [intridea/grape-entity#118]
`#represent` seems to ignore `only` option:

```ruby
class DummyEntity < Grape::Entity; expose :a, :b, :c; end # => [:a, :b, :c]
DummyEntity.represent({ a: 1, b: 2, c: 3}, only: [:b]).as_json # => {:a=>1, :b=>2, :c=>3}
```

An example from readme (`Returning only the fields you want` section) also doesn't work – it returns the full representation. By the way, inheritance from `Grape::Entity` is missing there.

Gem version: 0.4.5.

**Comment by dblock** [comment]
This is on HEAD? The `:only` support hasn't shipped yet.

**Comment by dblock** [comment]
I'll close this, please try on HEAD.
