### ISSUE TITLE
except: in the options

### ISSUE THREAD

**Issue by dan-corneanu** [intridea/grape-entity#123]
Since there is already support for only: in the options, could we also add except: ?
I would be happy to give it a try to implementing this feature if others find it useful.

**Comment by dblock** [comment]
:+1:

**Comment by estevaoam** [comment]
:+1:

**Comment by bswinnerton** [comment]
:+1:

**Comment by dan-corneanu** [comment]
Please review my pull request.

**Comment by marshall-lee** [comment]
Closing this as it's implemented in #135

**Comment by marshall-lee** [comment]
It's also included in 0.4.6 release that pushed to rubygems.
