### ISSUE TITLE
30-50% performance degradation after #126

### ISSUE THREAD

**Issue by etehtsea** [intridea/grape-entity#129]
Before https://github.com/intridea/grape-entity/pull/126:

**JRuby 1.7.19**

```
 jruby -G -S bench/serializing.rb
                   user     system      total        real
serializing    1.450000   0.020000   1.470000 (  1.254000)
```

**2.2.2**

```
                   user     system      total        real
serializing    1.750000   0.010000   1.760000 (  1.771028)
```

Now:

**JRuby 1.7.19**

```
                  user     system      total        real
serializing   2.270000   0.020000   2.290000 (  1.818000)
```

**2.2.2**

```
                  user     system      total        real
serializing   2.440000   0.020000   2.460000 (  2.500005)
```

I've got even worse results in some other scenarios.
And I think code becomes much more complicated after it.

**Comment by dblock** [comment]
Before we consider reverting anything, lets ping @u2.

**Comment by dblock** [comment]
@etehtsea Do you have a serializing.rb that someone can run with?

**Comment by etehtsea** [comment]
@dblock https://github.com/intridea/grape-entity/blob/master/bench/serializing.rb :)

**Comment by u2** [comment]
I will dive in it later.Do you have some suggestion about #126 @etehtsea .And is there some good gem for performance analyzing.

**Comment by etehtsea** [comment]
I don't feel that #56 is a serious issue to fix. At least not for a such price. Especially if suggested workaround works https://github.com/intridea/grape-entity/issues/52#issuecomment-49027130

About profiling tools:
- mri - https://github.com/tmm1/stackprof
- jruby - https://github.com/jruby/jruby/wiki/Profiling-jruby or jvisualvm/jprofiler

**Comment by u2** [comment]
Yes, I agree with you.So reverting it?
@dblock

**Comment by dblock** [comment]
Go ahead and PR reverting that, but I encourage you to spend a bit of time in a profiler because often it's something small and fixable.

**Comment by u2** [comment]
OK.Anyway I will do a profiler.

**Comment by dblock** [comment]
Reverted via https://github.com/intridea/grape-entity/pull/130.
