### ISSUE TITLE
`only` and `except` doesn't work

### ISSUE THREAD

**Issue by begin29** [intridea/grape-entity#148]
I have model User and model Klass. User belongs_to Klass as Category.

```ruby
class User < ActiveRecord::Base
 ...
  belongs_to :category, class_name: 'Klass', foreign_key: 'klass_id'

  class Entity < Grape::Entity
      expose :id
      expose :full_name
      expose :email
      expose :category, using: Klass::Entity
      expose :admin
  end
end

class Klass < ActiveRecord::Base
  has_many :subjects
  has_many :users

  validates_presence_of :name

  class Entity < Grape::Entity
    expose :id
    expose :name
  end

end

#my controller
...
data = User::Entity.represent( @user, only: [ :id, :full_name, :email, { category: [:id] } ] )
data.as_json # => {admin: null, category: {id: 7, name: "сьомий"}, email: "sdgfds@dsfgfsd.com", full_name: "sdgfds@dsfgfsd.com", id: 14}
```

I don`t know why, but I always get all fields. You can see source code here: 
https://github.com/begin29/schoolTest/tree/master/api

**Comment by dblock** [comment]
This hasn't shipped yet, it's on HEAD, are you pointing to HEAD?

**Comment by begin29** [comment]
Actually I read Readme page and expected that is working. 

Ok. I will try to update my `grape-entity` gem.

**Comment by begin29** [comment]
Yeah! It works for HEAD point. Thanks.

**Comment by dblock** [comment]
I understand, we need to have a warning like "you're reading the doc of the next development release ..." and update notes in RELEASING on how to edit this as you make a release as we do for Grape, maybe you can help with a PR?
