### ISSUE TITLE
unexposure is unaware of nesting

### ISSUE THREAD

**Issue by marshall-lee** [intridea/grape-entity#152]
```ruby
def self.unexpose(attribute)
  exposures.delete(attribute)
end
```
It just deletes attribute from `exposures` table. Of course, it's possible to call it like `unexpose(:some__nested)` but it's a hack that lacks internal representation which now is going to be removed(#151). It also doesn't clear the `nested_exposures` table which is potentially buggy.

I propose to temporarily forbid calling `unexpose` inside of nesting exposure (with exception) because it's unclear what to unexpose in this case. Current documentation says nothing about the calling `unexpose` withing nesting exposure so I think it's safe.

**Comment by marshall-lee** [comment]
For ones who want to 'unexpose' nested exposure for now the solution would be a good combination of conditional exposures(`:if`, `:unless`) and extracting nested things to separate entity classes (exposing via `:using`).

**Comment by dblock** [comment]
Right on @marshall-lee, your suggestion of raising an exception on `unexpose` inside nesting exposure is good.
